version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eppacher_master_thesis_dev
    privileged: true
    network_mode: host
    volumes:
      - ..:/Eppacher_Master_Thesis:cached
    command: sleep infinity
