services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eppacher_master_thesis_dev
    privileged: true
    network_mode: host
    volumes:
      - ..:/Eppacher_Master_Thesis:/Eppacher_Master_Thesis
    command: /bin/bash
    tty: true
    ipc: host
